# Generated by Django 4.2.3 on 2023-07-07 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("reservation_system", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(default=None, null=True)),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=200)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RenameField(
            model_name="reservation",
            old_name="end_time",
            new_name="check_in",
        ),
        migrations.RenameField(
            model_name="reservation",
            old_name="start_time",
            new_name="check_out",
        ),
        migrations.RenameField(
            model_name="reservation",
            old_name="choose_time",
            new_name="reservation_time",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="discount_price",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="purchased_time",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="status",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="tax_price",
        ),
        migrations.AddField(
            model_name="room",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="reservation_system.owner",
            ),
            preserve_default=False,
        ),
    ]
