# Generated by Django 4.2.3 on 2023-07-09 19:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "reservation_system",
            "0002_owner_rename_end_time_reservation_check_in_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="is_available",
        ),
    ]
